apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: mark-powell-demo
    app.kubernetes.io/part-of: mark-powell-demo
  name: mark-powell-demo
spec:
  ports:
  - name: 80-tcp
    protocol: TCP
    port: 80
    targetPort: 80
  - name: 3001-tcp
    protocol: TCP
    port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/name: mark-powell-demo
    app.kubernetes.io/part-of: app-mark-powell-demo
status:
  loadBalancer: {}